/*
 * Copyright (c) 2018, 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

#include "v8.h"
#include "org_openjdk_engine_javascript_internal_V8.h"

#include <assert.h>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/stat.h>
#include <unistd.h>

#include "jvmv8_jni.hpp"
#include "jvmv8_jni_support.hpp"
#include "jvmv8_java_classes.hpp"
#include "jvmv8.hpp"
#include "jvmv8_primitives.hpp"

// The following section will be regenerated by running genjavaclasses script. DO NOT EDIT.
// $BEGIN JAVA_CLASS_DECL
jclass objectClass = nullptr;
jmethodID objectClassToStringMethodID = nullptr;
jmethodID objectClassGetClassMethodID = nullptr;
jmethodID objectClassHashCodeMethodID = nullptr;
jclass classClass = nullptr;
jmethodID classGetNameMethodID = nullptr;
jmethodID classIsArrayMethodID = nullptr;
jmethodID classIsPrimitiveMethodID = nullptr;
jmethodID classGetComponentTypeMethodID = nullptr;
jclass numberClass = nullptr;
jmethodID numberFloatValueMethodID = nullptr;
jmethodID numberDoubleValueMethodID = nullptr;
jmethodID numberIntValueMethodID = nullptr;
jmethodID numberLongValueMethodID = nullptr;
jclass booleanClass = nullptr;
jmethodID booleanBooleanValueMethodID = nullptr;
jmethodID booleanValueOfMethodID = nullptr;
jclass byteClass = nullptr;
jmethodID byteValueOfMethodID = nullptr;
jclass shortClass = nullptr;
jmethodID shortValueOfMethodID = nullptr;
jclass integerClass = nullptr;
jmethodID integerValueOfMethodID = nullptr;
jclass longClass = nullptr;
jmethodID longValueOfMethodID = nullptr;
jclass floatClass = nullptr;
jmethodID floatValueOfMethodID = nullptr;
jclass doubleClass = nullptr;
jmethodID doubleValueOfMethodID = nullptr;
jclass stringClass = nullptr;
jclass characterClass = nullptr;
jmethodID characterCharValueMethodID = nullptr;
jmethodID characterValueOfMethodID = nullptr;
jclass noClassDefFoundErrorClass = nullptr;
jclass v8Class = nullptr;
jmethodID v8ClassInitializeMethodID = nullptr;
jmethodID v8ClassFieldSignatureMethodID = nullptr;
jmethodID v8ClassExecutableSignatureMethodID = nullptr;
jmethodID v8ClassResolveModuleMethodID = nullptr;
jmethodID v8GenerateClassMethodID = nullptr;
jmethodID v8LookupPropertyMethodID = nullptr;
jmethodID v8GetInterfaceMethodID = nullptr;
jmethodID v8GetBootstrapMethodID = nullptr;
jmethodID v8FindClassMethodID = nullptr;
jmethodID v8FindClassPrivateMethodID = nullptr;
jmethodID v8CreateListAdapterMethodID = nullptr;
jmethodID v8NewByteBufferMethodID = nullptr;
jmethodID v8StringPropAttrFlagsMethodID = nullptr;
jmethodID v8SymbolPropAttrFlagsMethodID = nullptr;
jmethodID v8IntPropAttrFlagsMethodID = nullptr;
jmethodID v8jsObjectGetMemberMethodID = nullptr;
jmethodID v8InspectorSendResponseMethodID = nullptr;
jmethodID v8InspectorSendNotificationMethodID = nullptr;
jmethodID v8InspectorRunMessageLoopOnPauseMethodID = nullptr;
jmethodID v8InspectorQuitMessageLoopOnPauseMethodID = nullptr;
jclass v8ObjectClass = nullptr;
jmethodID v8ObjectCreateMethodID = nullptr;
jmethodID v8ObjectCheckAndGetReferenceMethodID = nullptr;
jclass v8ArrayClass = nullptr;
jmethodID v8ArrayCreateMethodID = nullptr;
jclass v8TypedArrayClass = nullptr;
jmethodID v8TypedArrayCreateMethodID = nullptr;
jclass v8FunctionClass = nullptr;
jmethodID v8FunctionCreateMethodID = nullptr;
jclass v8PromiseClass = nullptr;
jmethodID v8PromiseCreateMethodID = nullptr;
jclass v8ProxyClass = nullptr;
jmethodID v8ProxyCreateMethodID = nullptr;
jclass v8ResolverClass = nullptr;
jmethodID v8ResolverCreateMethodID = nullptr;
jclass v8UndefinedClass = nullptr;
jfieldID v8UndefinedInstanceFieldID = nullptr;
jclass v8SymbolClass = nullptr;
jmethodID v8SymbolCreateMethodID = nullptr;
jmethodID v8SymbolCheckAndGetReferenceMethodID = nullptr;
jclass v8ScriptExceptionClass = nullptr;
jmethodID v8ScriptExceptionInitMethodID = nullptr;
jclass runtimeExceptionClass = nullptr;
jclass v8GlobalFunctionsClass = nullptr;
jmethodID v8GlobalFunctionsLoadMethodID = nullptr;
jmethodID v8GlobalFunctionsForkOnExecutorMethodID = nullptr;
jmethodID v8GlobalFunctionsPrintMethodID = nullptr;
jclass jsObjectClass = nullptr;
jmethodID jsObjectIsCallableMethodID = nullptr;
jmethodID jsObjectCallMethodID = nullptr;
jmethodID jsObjectNewObjectMethodID = nullptr;
jmethodID jsObjectGetMemberMethodID = nullptr;
jmethodID jsObjectSetMemberMethodID = nullptr;
jmethodID jsObjectHasMemberMethodID = nullptr;
jmethodID jsObjectRemoveMemberMethodID = nullptr;
jmethodID jsObjectGetNamedPropertiesMethodID = nullptr;
jmethodID jsObjectGetMemberSymbolMethodID = nullptr;
jmethodID jsObjectSetMemberSymbolMethodID = nullptr;
jmethodID jsObjectHasMemberSymbolMethodID = nullptr;
jmethodID jsObjectRemoveMemberSymbolMethodID = nullptr;
jmethodID jsObjectGetSymbolPropertiesMethodID = nullptr;
jmethodID jsObjectGetSlotMethodID = nullptr;
jmethodID jsObjectSetSlotMethodID = nullptr;
jmethodID jsObjectHasSlotMethodID = nullptr;
jmethodID jsObjectRemoveSlotMethodID = nullptr;
jmethodID jsObjectGetIndexedPropertiesMethodID = nullptr;
jclass jsFunctionClass = nullptr;
jmethodID jsFunctionCallMethodID = nullptr;
jmethodID jsFunctionNewObjectMethodID = nullptr;
jclass runnableClass = nullptr;
jmethodID runnableRunMethodID = nullptr;
jclass illegalArgumentExceptionClass = nullptr;
jclass stackTraceElementClass = nullptr;
jmethodID stackTraceElementClassInitMethodID = nullptr;
jclass throwableClass = nullptr;
jmethodID throwableClassGetMessageMethodID = nullptr;
jclass byteBufferClass = nullptr;
jclass booleanPrimitiveArrayClass = nullptr;
jclass bytePrimitiveArrayClass = nullptr;
jclass shortPrimitiveArrayClass = nullptr;
jclass characterPrimitiveArrayClass = nullptr;
jclass integerPrimitiveArrayClass = nullptr;
jclass longPrimitiveArrayClass = nullptr;
jclass floatPrimitiveArrayClass = nullptr;
jclass doublePrimitiveArrayClass = nullptr;
jclass booleanWrapperArrayClass = nullptr;
jclass byteWrapperArrayClass = nullptr;
jclass shortWrapperArrayClass = nullptr;
jclass characterWrapperArrayClass = nullptr;
jclass integerWrapperArrayClass = nullptr;
jclass longWrapperArrayClass = nullptr;
jclass floatWrapperArrayClass = nullptr;
jclass doubleWrapperArrayClass = nullptr;
jclass objectArrayClass = nullptr;
jclass stringArrayClass = nullptr;
// $END JAVA_CLASS_DECL


void initJVMV8Classes(JNIEnv* env) {
   JNI jni(env);

// The following section is used by running genjavaclasses script to generate other sections. MAY EDIT.
// BUT, FOLLOW PATTERNS. Names ending with
//    "Class" - will be treated as Java classes
//    "MethodID" - will be treated as Java methods
//    "FieldID" - will be treated as Java fields
// $BEGIN JAVA_CLASS_LOOKUP
    objectClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Object"));

    objectClassToStringMethodID = jni.GetMethodID(objectClass, "toString", "()Ljava/lang/String;");
    objectClassGetClassMethodID = jni.GetMethodID(objectClass, "getClass", "()Ljava/lang/Class;");
    objectClassHashCodeMethodID = jni.GetMethodID(objectClass, "hashCode", "()I");

    classClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Class"));
    classGetNameMethodID = jni.GetMethodID(classClass, "getName", "()Ljava/lang/String;");
    classIsArrayMethodID = jni.GetMethodID(classClass, "isArray", "()Z");
    classIsPrimitiveMethodID = jni.GetMethodID(classClass, "isPrimitive", "()Z");
    classGetComponentTypeMethodID = jni.GetMethodID(classClass, "getComponentType", "()Ljava/lang/Class;");

    numberClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Number"));
    numberFloatValueMethodID = jni.GetMethodID(numberClass, "floatValue", "()F");
    numberDoubleValueMethodID = jni.GetMethodID(numberClass, "doubleValue", "()D");
    numberIntValueMethodID = jni.GetMethodID(numberClass, "intValue", "()I");
    numberLongValueMethodID = jni.GetMethodID(numberClass, "longValue", "()J");

    booleanClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Boolean"));
    booleanBooleanValueMethodID = jni.GetMethodID(booleanClass, "booleanValue", "()Z");
    booleanValueOfMethodID = jni.GetStaticMethodID(booleanClass, "valueOf", "(Z)Ljava/lang/Boolean;");

    byteClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Byte"));
    byteValueOfMethodID = jni.GetStaticMethodID(byteClass, "valueOf", "(B)Ljava/lang/Byte;");

    shortClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Short"));
    shortValueOfMethodID = jni.GetStaticMethodID(shortClass, "valueOf", "(S)Ljava/lang/Short;");

    integerClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Integer"));
    integerValueOfMethodID = jni.GetStaticMethodID(integerClass, "valueOf", "(I)Ljava/lang/Integer;");

    longClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Long"));
    longValueOfMethodID = jni.GetStaticMethodID(longClass, "valueOf", "(J)Ljava/lang/Long;");

    floatClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Float"));
    floatValueOfMethodID = jni.GetStaticMethodID(floatClass, "valueOf", "(F)Ljava/lang/Float;");

    doubleClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Double"));
    doubleValueOfMethodID = jni.GetStaticMethodID(doubleClass, "valueOf", "(D)Ljava/lang/Double;");

    stringClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/String"));

    characterClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Character"));
    characterCharValueMethodID = jni.GetMethodID(characterClass, "charValue", "()C");
    characterValueOfMethodID = jni.GetStaticMethodID(characterClass, "valueOf", "(C)Ljava/lang/Character;");

    noClassDefFoundErrorClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/NoClassDefFoundError"));

    v8Class = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8"));

    v8ClassInitializeMethodID = jni.GetStaticMethodID(v8Class, "initialize", "()V");
    v8ClassFieldSignatureMethodID = jni.GetStaticMethodID(v8Class, "fieldSignature", "(Ljava/lang/reflect/Field;)Ljava/lang/String;");
    v8ClassExecutableSignatureMethodID = jni.GetStaticMethodID(v8Class, "executableSignature", "(Ljava/lang/reflect/Executable;)Ljava/lang/String;");
    v8ClassResolveModuleMethodID = jni.GetStaticMethodID(v8Class, "resolveModule", "(Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;");
    v8GenerateClassMethodID = jni.GetStaticMethodID(v8Class, "generateClass", "(Ljava/lang/Class;)Ljava/lang/String;");
    v8LookupPropertyMethodID = jni.GetStaticMethodID(v8Class, "lookupProperty", "(Ljava/lang/Class;Ljava/lang/String;Z)Ljava/lang/String;");
    v8GetInterfaceMethodID = jni.GetStaticMethodID(v8Class, "getInterface", "(Ljava/lang/Class;L" V8_INTERNAL_PACKAGE_PREFIX "V8Object;)Ljava/lang/Object;");
    v8GetBootstrapMethodID = jni.GetStaticMethodID(v8Class, "getBootstrap", "()Ljava/lang/String;");
    v8FindClassMethodID = jni.GetStaticMethodID(v8Class, "findClass", "(Ljava/lang/String;)Ljava/lang/Class;");
    v8FindClassPrivateMethodID = jni.GetStaticMethodID(v8Class, "findClassPrivate", "(Ljava/lang/String;)Ljava/lang/Class;");
    v8CreateListAdapterMethodID = jni.GetStaticMethodID(v8Class, "createListAdapter", "(L" V8_PACKAGE_PREFIX "JSObject;Ljava/lang/Class;)L" V8_INTERNAL_PACKAGE_PREFIX "ListAdapter;");
    v8NewByteBufferMethodID = jni.GetStaticMethodID(v8Class, "newByteBuffer", "(L" V8_INTERNAL_PACKAGE_PREFIX "V8Object;)Ljava/nio/ByteBuffer;");
    v8StringPropAttrFlagsMethodID = jni.GetStaticMethodID(v8Class, "propertyAttributeFlags", "(L" V8_PACKAGE_PREFIX "JSObject;Ljava/lang/String;)I");
    v8SymbolPropAttrFlagsMethodID = jni.GetStaticMethodID(v8Class, "propertyAttributeFlags", "(L" V8_PACKAGE_PREFIX "JSObject;L" V8_PACKAGE_PREFIX "JSSymbol;)I");
    v8IntPropAttrFlagsMethodID = jni.GetStaticMethodID(v8Class, "propertyAttributeFlags", "(L" V8_PACKAGE_PREFIX "JSObject;I)I");
    v8jsObjectGetMemberMethodID = jni.GetStaticMethodID(v8Class, "jsObjectGetMember", "(L" V8_PACKAGE_PREFIX  "JSObject;Ljava/lang/String;)Ljava/lang/Object;");
    v8InspectorSendResponseMethodID = jni.GetStaticMethodID(v8Class, "inspectorSendResponse", "(L" V8_INTERNAL_PACKAGE_PREFIX "V8Isolate;ILjava/lang/String;)V");
    v8InspectorSendNotificationMethodID = jni.GetStaticMethodID(v8Class, "inspectorSendNotification", "(L" V8_INTERNAL_PACKAGE_PREFIX "V8Isolate;Ljava/lang/String;)V");
    v8InspectorRunMessageLoopOnPauseMethodID = jni.GetStaticMethodID(v8Class, "inspectorRunMessageLoopOnPause", "(L" V8_INTERNAL_PACKAGE_PREFIX "V8Isolate;)V");
    v8InspectorQuitMessageLoopOnPauseMethodID = jni.GetStaticMethodID(v8Class, "inspectorQuitMessageLoopOnPause", "(L" V8_INTERNAL_PACKAGE_PREFIX "V8Isolate;)V");

    v8ObjectClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Object"));
    v8ObjectCreateMethodID = jni.GetStaticMethodID(v8ObjectClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8Object;");
    v8ObjectCheckAndGetReferenceMethodID = jni.GetMethodID(v8ObjectClass, "checkAndGetReference", "(J)J");

    v8ArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Array"));
    v8ArrayCreateMethodID = jni.GetStaticMethodID(v8ArrayClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8Array;");

    v8TypedArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8TypedArray"));
    v8TypedArrayCreateMethodID = jni.GetStaticMethodID(v8TypedArrayClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8TypedArray;");

    v8FunctionClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Function"));
    v8FunctionCreateMethodID = jni.GetStaticMethodID(v8FunctionClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8Function;");

    v8PromiseClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Promise"));
    v8PromiseCreateMethodID = jni.GetStaticMethodID(v8PromiseClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8Promise;");

    v8ProxyClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Proxy"));
    v8ProxyCreateMethodID = jni.GetStaticMethodID(v8ProxyClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8Proxy;");

    v8ResolverClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Resolver"));
    v8ResolverCreateMethodID = jni.GetStaticMethodID(v8ResolverClass, "create", "(J)L" V8_INTERNAL_PACKAGE_PREFIX "V8Resolver;");

    v8UndefinedClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_PACKAGE_PREFIX "V8Undefined"));
    v8UndefinedInstanceFieldID = jni.GetStaticFieldID(v8UndefinedClass, "INSTANCE", "L" V8_PACKAGE_PREFIX "V8Undefined;");

    v8SymbolClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8Symbol"));
    v8SymbolCreateMethodID = jni.GetStaticMethodID(v8SymbolClass, "create", "(JLjava/lang/String;)L" V8_INTERNAL_PACKAGE_PREFIX "V8Symbol;");
    v8SymbolCheckAndGetReferenceMethodID = jni.GetMethodID(v8SymbolClass, "checkAndGetReference", "(J)J");

    v8ScriptExceptionClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_PACKAGE_PREFIX "V8ScriptException"));
    v8ScriptExceptionInitMethodID = jni.GetMethodID(v8ScriptExceptionClass, "<init>", "(Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Ljava/lang/Object;)V");

    runtimeExceptionClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/RuntimeException"));

    v8GlobalFunctionsClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_INTERNAL_PACKAGE_PREFIX "V8GlobalFunctions"));
    v8GlobalFunctionsLoadMethodID = jni.GetStaticMethodID(v8GlobalFunctionsClass, "load", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
    v8GlobalFunctionsForkOnExecutorMethodID = jni.GetStaticMethodID(v8GlobalFunctionsClass,
        "forkOnExecutor", "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;");
    v8GlobalFunctionsPrintMethodID = jni.GetStaticMethodID(v8GlobalFunctionsClass, "print", "(Ljava/lang/Object;[Ljava/lang/Object;)V");
    jsObjectClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_PACKAGE_PREFIX "JSObject"));
    jsObjectIsCallableMethodID = jni.GetMethodID(jsObjectClass, "isCallable", "()Z");
    jsObjectCallMethodID = jni.GetMethodID(jsObjectClass, "call", "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;");
    jsObjectNewObjectMethodID = jni.GetMethodID(jsObjectClass, "newObject", "([Ljava/lang/Object;)Ljava/lang/Object;");
    jsObjectGetMemberMethodID = jni.GetMethodID(jsObjectClass, "getMember", "(Ljava/lang/String;)Ljava/lang/Object;");
    jsObjectSetMemberMethodID = jni.GetMethodID(jsObjectClass, "setMember", "(Ljava/lang/String;Ljava/lang/Object;)Z");
    jsObjectHasMemberMethodID = jni.GetMethodID(jsObjectClass, "hasMember", "(Ljava/lang/String;)Z");
    jsObjectRemoveMemberMethodID = jni.GetMethodID(jsObjectClass, "removeMember", "(Ljava/lang/String;)Z");
    jsObjectGetNamedPropertiesMethodID = jni.GetMethodID(jsObjectClass, "getNamedProperties", "()[Ljava/lang/String;");
    jsObjectGetMemberSymbolMethodID = jni.GetMethodID(jsObjectClass, "getMember", "(Lorg/openjdk/engine/javascript/JSSymbol;)Ljava/lang/Object;");
    jsObjectSetMemberSymbolMethodID = jni.GetMethodID(jsObjectClass, "setMember", "(Lorg/openjdk/engine/javascript/JSSymbol;Ljava/lang/Object;)Z");
    jsObjectHasMemberSymbolMethodID = jni.GetMethodID(jsObjectClass, "hasMember", "(Lorg/openjdk/engine/javascript/JSSymbol;)Z");
    jsObjectRemoveMemberSymbolMethodID = jni.GetMethodID(jsObjectClass, "removeMember", "(Lorg/openjdk/engine/javascript/JSSymbol;)Z");
    jsObjectGetSymbolPropertiesMethodID = jni.GetMethodID(jsObjectClass, "getSymbolProperties", "()[Lorg/openjdk/engine/javascript/JSSymbol;");
    jsObjectGetSlotMethodID = jni.GetMethodID(jsObjectClass, "getSlot", "(I)Ljava/lang/Object;");
    jsObjectSetSlotMethodID = jni.GetMethodID(jsObjectClass, "setSlot", "(ILjava/lang/Object;)Z");
    jsObjectHasSlotMethodID = jni.GetMethodID(jsObjectClass, "hasSlot", "(I)Z");
    jsObjectRemoveSlotMethodID = jni.GetMethodID(jsObjectClass, "removeSlot", "(I)Z");
    jsObjectGetIndexedPropertiesMethodID = jni.GetMethodID(jsObjectClass, "getIndexedProperties", "()[I");

    jsFunctionClass = (jclass)jni.NewGlobalRef(jni.FindClass(V8_PACKAGE_PREFIX "JSFunction"));
    jsFunctionCallMethodID = jni.GetMethodID(jsFunctionClass, "call", "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;");
    jsFunctionNewObjectMethodID = jni.GetMethodID(jsFunctionClass, "newObject", "([Ljava/lang/Object;)Ljava/lang/Object;");

    runnableClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/Runnable"));
    runnableRunMethodID = jni.GetMethodID(runnableClass, "run", "()V");

    illegalArgumentExceptionClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/IllegalArgumentException"));

    stackTraceElementClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/lang/StackTraceElement"));
    stackTraceElementClassInitMethodID = jni.GetMethodID(stackTraceElementClass,
            "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V");

    throwableClass = (jclass)env->NewGlobalRef(env->FindClass("java/lang/Throwable"));
    throwableClassGetMessageMethodID = env->GetMethodID(throwableClass, "getMessage", "()Ljava/lang/String;");

    byteBufferClass = (jclass)jni.NewGlobalRef(jni.FindClass("java/nio/ByteBuffer"));

    booleanPrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Z"));
    bytePrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[B"));
    shortPrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[S"));
    characterPrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[C"));
    integerPrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[I"));
    longPrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[J"));
    floatPrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[F"));
    doublePrimitiveArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[D"));

    booleanWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Boolean;"));
    byteWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Byte;"));
    shortWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Short;"));
    characterWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Character;"));
    integerWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Integer;"));
    longWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Long;"));
    floatWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Float;"));
    doubleWrapperArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Double;"));

    objectArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/Object;"));
    stringArrayClass = (jclass)jni.NewGlobalRef(jni.FindClass("[Ljava/lang/String;"));
// $END JAVA_CLASS_LOOKUP
}

void termJVMV8Classes(JNIEnv* env) {
   JNI jni(env);

// The following section can be regenerated by running genjavaclasses script.
// $BEGIN JAVA_CLASS_DELETE
    jni.DeleteGlobalRef(objectClass);
    jni.DeleteGlobalRef(classClass);
    jni.DeleteGlobalRef(numberClass);
    jni.DeleteGlobalRef(booleanClass);
    jni.DeleteGlobalRef(byteClass);
    jni.DeleteGlobalRef(shortClass);
    jni.DeleteGlobalRef(integerClass);
    jni.DeleteGlobalRef(longClass);
    jni.DeleteGlobalRef(floatClass);
    jni.DeleteGlobalRef(doubleClass);
    jni.DeleteGlobalRef(stringClass);
    jni.DeleteGlobalRef(characterClass);
    jni.DeleteGlobalRef(noClassDefFoundErrorClass);
    jni.DeleteGlobalRef(v8Class);
    jni.DeleteGlobalRef(v8ObjectClass);
    jni.DeleteGlobalRef(v8ArrayClass);
    jni.DeleteGlobalRef(v8TypedArrayClass);
    jni.DeleteGlobalRef(v8FunctionClass);
    jni.DeleteGlobalRef(v8PromiseClass);
    jni.DeleteGlobalRef(v8ProxyClass);
    jni.DeleteGlobalRef(v8ResolverClass);
    jni.DeleteGlobalRef(v8UndefinedClass);
    jni.DeleteGlobalRef(v8SymbolClass);
    jni.DeleteGlobalRef(v8ScriptExceptionClass);
    jni.DeleteGlobalRef(runtimeExceptionClass);
    jni.DeleteGlobalRef(v8GlobalFunctionsClass);
    jni.DeleteGlobalRef(jsObjectClass);
    jni.DeleteGlobalRef(jsFunctionClass);
    jni.DeleteGlobalRef(runnableClass);
    jni.DeleteGlobalRef(illegalArgumentExceptionClass);
    jni.DeleteGlobalRef(stackTraceElementClass);
    jni.DeleteGlobalRef(throwableClass);
    jni.DeleteGlobalRef(byteBufferClass);
    jni.DeleteGlobalRef(booleanPrimitiveArrayClass);
    jni.DeleteGlobalRef(bytePrimitiveArrayClass);
    jni.DeleteGlobalRef(shortPrimitiveArrayClass);
    jni.DeleteGlobalRef(characterPrimitiveArrayClass);
    jni.DeleteGlobalRef(integerPrimitiveArrayClass);
    jni.DeleteGlobalRef(longPrimitiveArrayClass);
    jni.DeleteGlobalRef(floatPrimitiveArrayClass);
    jni.DeleteGlobalRef(doublePrimitiveArrayClass);
    jni.DeleteGlobalRef(booleanWrapperArrayClass);
    jni.DeleteGlobalRef(byteWrapperArrayClass);
    jni.DeleteGlobalRef(shortWrapperArrayClass);
    jni.DeleteGlobalRef(characterWrapperArrayClass);
    jni.DeleteGlobalRef(integerWrapperArrayClass);
    jni.DeleteGlobalRef(longWrapperArrayClass);
    jni.DeleteGlobalRef(floatWrapperArrayClass);
    jni.DeleteGlobalRef(doubleWrapperArrayClass);
    jni.DeleteGlobalRef(objectArrayClass);
    jni.DeleteGlobalRef(stringArrayClass);
// $END JAVA_CLASS_DELETE

}
