/*
 * Copyright (c) 2018, 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

#ifndef __jvmv8_java_classes_hpp__
#define __jvmv8_java_classes_hpp__

extern void initJVMV8Classes(JNIEnv* env);
extern void termJVMV8Classes(JNIEnv* env);

// The following section can be regenerated by running genjavaclasses script. DO NOT EDIT.
// $BEGIN JAVA_CLASS_EXTERN
extern jclass objectClass;
extern jmethodID objectClassToStringMethodID;
extern jmethodID objectClassGetClassMethodID;
extern jmethodID objectClassHashCodeMethodID;
extern jclass classClass;
extern jmethodID classGetNameMethodID;
extern jmethodID classIsArrayMethodID;
extern jmethodID classIsPrimitiveMethodID;
extern jmethodID classGetComponentTypeMethodID;
extern jclass numberClass;
extern jmethodID numberFloatValueMethodID;
extern jmethodID numberDoubleValueMethodID;
extern jmethodID numberIntValueMethodID;
extern jmethodID numberLongValueMethodID;
extern jclass booleanClass;
extern jmethodID booleanBooleanValueMethodID;
extern jmethodID booleanValueOfMethodID;
extern jclass byteClass;
extern jmethodID byteValueOfMethodID;
extern jclass shortClass;
extern jmethodID shortValueOfMethodID;
extern jclass integerClass;
extern jmethodID integerValueOfMethodID;
extern jclass longClass;
extern jmethodID longValueOfMethodID;
extern jclass floatClass;
extern jmethodID floatValueOfMethodID;
extern jclass doubleClass;
extern jmethodID doubleValueOfMethodID;
extern jclass stringClass;
extern jclass characterClass;
extern jmethodID characterCharValueMethodID;
extern jmethodID characterValueOfMethodID;
extern jclass noClassDefFoundErrorClass;
extern jclass v8Class;
extern jmethodID v8ClassInitializeMethodID;
extern jmethodID v8ClassFieldSignatureMethodID;
extern jmethodID v8ClassExecutableSignatureMethodID;
extern jmethodID v8ClassResolveModuleMethodID;
extern jmethodID v8GenerateClassMethodID;
extern jmethodID v8LookupPropertyMethodID;
extern jmethodID v8GetInterfaceMethodID;
extern jmethodID v8GetBootstrapMethodID;
extern jmethodID v8FindClassMethodID;
extern jmethodID v8FindClassPrivateMethodID;
extern jmethodID v8CreateListAdapterMethodID;
extern jmethodID v8NewByteBufferMethodID;
extern jmethodID v8StringPropAttrFlagsMethodID;
extern jmethodID v8SymbolPropAttrFlagsMethodID;
extern jmethodID v8IntPropAttrFlagsMethodID;
extern jmethodID v8jsObjectGetMemberMethodID;
extern jmethodID v8InspectorSendResponseMethodID;
extern jmethodID v8InspectorSendNotificationMethodID;
extern jmethodID v8InspectorRunMessageLoopOnPauseMethodID;
extern jmethodID v8InspectorQuitMessageLoopOnPauseMethodID;
extern jclass v8ObjectClass;
extern jmethodID v8ObjectCreateMethodID;
extern jmethodID v8ObjectCheckAndGetReferenceMethodID;
extern jclass v8ArrayClass;
extern jmethodID v8ArrayCreateMethodID;
extern jclass v8TypedArrayClass;
extern jmethodID v8TypedArrayCreateMethodID;
extern jclass v8FunctionClass;
extern jmethodID v8FunctionCreateMethodID;
extern jclass v8PromiseClass;
extern jmethodID v8PromiseCreateMethodID;
extern jclass v8ProxyClass;
extern jmethodID v8ProxyCreateMethodID;
extern jclass v8ResolverClass;
extern jmethodID v8ResolverCreateMethodID;
extern jclass v8UndefinedClass;
extern jfieldID v8UndefinedInstanceFieldID;
extern jclass v8SymbolClass;
extern jmethodID v8SymbolCreateMethodID;
extern jmethodID v8SymbolCheckAndGetReferenceMethodID;
extern jclass v8ScriptExceptionClass;
extern jmethodID v8ScriptExceptionInitMethodID;
extern jclass runtimeExceptionClass;
extern jclass v8GlobalFunctionsClass;
extern jmethodID v8GlobalFunctionsLoadMethodID;
extern jmethodID v8GlobalFunctionsForkOnExecutorMethodID;
extern jmethodID v8GlobalFunctionsPrintMethodID;
extern jclass jsObjectClass;
extern jmethodID jsObjectIsCallableMethodID;
extern jmethodID jsObjectCallMethodID;
extern jmethodID jsObjectNewObjectMethodID;
extern jmethodID jsObjectGetMemberMethodID;
extern jmethodID jsObjectSetMemberMethodID;
extern jmethodID jsObjectHasMemberMethodID;
extern jmethodID jsObjectRemoveMemberMethodID;
extern jmethodID jsObjectGetNamedPropertiesMethodID;
extern jmethodID jsObjectGetMemberSymbolMethodID;
extern jmethodID jsObjectSetMemberSymbolMethodID;
extern jmethodID jsObjectHasMemberSymbolMethodID;
extern jmethodID jsObjectRemoveMemberSymbolMethodID;
extern jmethodID jsObjectGetSymbolPropertiesMethodID;
extern jmethodID jsObjectGetSlotMethodID;
extern jmethodID jsObjectSetSlotMethodID;
extern jmethodID jsObjectHasSlotMethodID;
extern jmethodID jsObjectRemoveSlotMethodID;
extern jmethodID jsObjectGetIndexedPropertiesMethodID;
extern jclass jsFunctionClass;
extern jmethodID jsFunctionCallMethodID;
extern jmethodID jsFunctionNewObjectMethodID;
extern jclass runnableClass;
extern jmethodID runnableRunMethodID;
extern jclass illegalArgumentExceptionClass;
extern jclass stackTraceElementClass;
extern jmethodID stackTraceElementClassInitMethodID;
extern jclass throwableClass;
extern jmethodID throwableClassGetMessageMethodID;
extern jclass byteBufferClass;
extern jclass booleanPrimitiveArrayClass;
extern jclass bytePrimitiveArrayClass;
extern jclass shortPrimitiveArrayClass;
extern jclass characterPrimitiveArrayClass;
extern jclass integerPrimitiveArrayClass;
extern jclass longPrimitiveArrayClass;
extern jclass floatPrimitiveArrayClass;
extern jclass doublePrimitiveArrayClass;
extern jclass booleanWrapperArrayClass;
extern jclass byteWrapperArrayClass;
extern jclass shortWrapperArrayClass;
extern jclass characterWrapperArrayClass;
extern jclass integerWrapperArrayClass;
extern jclass longWrapperArrayClass;
extern jclass floatWrapperArrayClass;
extern jclass doubleWrapperArrayClass;
extern jclass objectArrayClass;
extern jclass stringArrayClass;
// $END JAVA_CLASS_EXTERN

#endif // __jvmv8_java_classes_hpp__
