#
# Copyright (c) 2018, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

option.error.invalid.option="{0}" is not a recognized option. Use "{1}" or "{2}" to see a list of all supported options.

jvmv8.options = Usage: jvmv8 [option=value]* [filename.js]+ [-- options...]\n\
                \n\
                Valid options are:

#
# Localized meta descriptions
#
jvmv8.options.param = param
jvmv8.options.default = default

#
# Which option is "help".
#
jvmv8.options.help.key = jvmv8.option.help

#
# Which option is "xhelp".
#
jvmv8.options.xhelp.key = jvmv8.option.xhelp

#
# Which option is "D".
#
jvmv8.options.D.key = jvmv8.option.D

##
## Grammar: at least short or long form. Arguments are optional, in that case they are given as
##
## params - a description of the parameters for command line usage
## name - the name of the option, e.g. "--long-name"
## short_name - the short name of the option, e.g. "-l"
## type - the type of the option, currently allowed: boolean, integer, string, log, timezone. defaults to boolean if left out
## is_undocumented - should this option never appear in the online help. defaults to no.
## desc - description of what the option does
## default - default value of the option. e.g. debug.lines is true by default. Not set means option not available by default
## dependency - does this arg imply another arg.
## confict - does this arg conflict with another arg e.g trace && instrument
## value_next_arg - is the opton's value passed as next argument in command line?
##
## At least short_name or name needs to be in place for an argument descriptor to be valid.

jvmv8.option.help = {                       \
    name="-help",                             \
    short_name="-h",                          \
    desc="Print help for command line flags." \
}

jvmv8.option.xhelp = {                               \
    name="-xhelp",                                     \
    is_undocumented=true,                              \
    desc="Print extended help for command line flags." \
}

jvmv8.option.classpath ={                                   \
    name="-classpath",                                        \
    short_name="-cp",                                         \
    desc="-cp path. Specify where to find user class files.", \
    value_next_arg=true,                                      \
    type=String                                               \
}

jvmv8.option.d = {                                             \
    name="--dump-debug-dir",                                     \
    short_name="-d",                                             \
    is_undocumented=true,                                        \
    params="<path>",                                             \
    desc="specify a destination directory to dump source and class files.", \
    type=String                                                  \
}

jvmv8.option.D = {                                                          \
    name="-D",                                                                \
    desc="-Dname=value. Set a system property. This option can be repeated.", \
    type=String                                                               \
}

jvmv8.option.doe = {                   \
    name="-dump-on-error",               \
    short_name="-doe",                   \
    desc="Dump a stack trace on errors." \
}

jvmv8.option.fullversion = {                 \
    name="-fullversion",                       \
    short_name="-fv",                          \
    desc="Print full version info of jvmv8." \
}

jvmv8.option.print.no.newline = {                     \
    name="--print-no-newline",                          \
    is_undocumented=true,                               \
    desc="Print function will not print new line char." \
}

jvmv8.option.stdout = {                                                \
    name="--stdout",                                                     \
    is_undocumented=true,                                                \
    type=String,                                                         \
    params="<output console>",                                           \
    desc="Redirect stdout to a filename or to another tty, e.g. stderr." \
}

jvmv8.option.stderr = {                                                \
    name="--stderr",                                                     \
    is_undocumented=true,                                                \
    type=String,                                                         \
    params="<output console>",                                           \
    desc="Redirect stderr to a filename or to another tty, e.g. stdout." \
}

jvmv8.option.timezone = {                    \
    name="-timezone",                          \
    short_name="-t",                           \
    params="<timezone>",                       \
    desc="Set timezone for script execution.", \
    type=TimeZone                              \
}

jvmv8.option.version = {                \
    name="-version",                      \
    short_name="-v",                      \
    desc="Print version info of jvmv8." \
}

